---
# tasks file for bvansomeren.bhyve-guest

- debug:
    var: "{{ item }}"
  with_items: "{{ bhyve_vms }}"

- include: setup.yml

- name: ensure kickstart file for VM
  template:
    src: "{{ item.os.kickstart }}"
    dest: "{{ ksroot }}/{{ item.name }}.ks"
  with_items: "{{ bhyve_vms }}"

- name: ensure ZFS root for VM
  zfs:
    name: "{{ bhyve_dataset }}/{{ item.name }}"
    state: present
  with_items: "{{ bhyve_vms }}"

- name: ensure ZFS root ZVOL for VM
  zfs:
    name: "{{ bhyve_dataset }}/{{ item.name }}/root"
    state: present
    compression: lz4
    volsize: "{{ item.root }}m"
  with_items: "{{ bhyve_vms }}"

- name: ensure ZFS swap ZVOL for VM
  zfs:
    name: "{{ bhyve_dataset }}/{{ item.name }}/swap"
    state: present
    sync: disabled
    volsize: "{{ item.swap }}m"
  with_items: "{{ bhyve_vms }}"

- name: check current virtual machines
  command: ls /dev/vmm/
  ignore_errors: yes
  register: vms

- name: create install script for VM
  template: 
    src: install.sh 
    dest: "{{ bhyve_mountpoint }}/{{ item.name }}/{{ item.name }}-install.sh" 
    mode: 0700
  with_items: "{{ bhyve_vms }}"

- name: create start script for VM
  template: 
    src: start.sh 
    dest: "{{ bhyve_mountpoint }}/{{ item.name }}/start.sh" 
    mode: 0700
  with_items: "{{ bhyve_vms }}"

- name: create install grub file for VM
  template:
    src: grub.doinstall
    dest: "{{ bhyve_mountpoint }}/{{ item.name }}/grub.doinstall"
  with_items: "{{ bhyve_vms }}"

- name: create device.install.map
  template:
    src: device.install.map
    dest: "{{ bhyve_mountpoint }}/{{ item.name }}/device.install.map"
  with_items: "{{ bhyve_vms }}"

- name: create start grub file for VM
  template:
    src: grub.installed
    dest: "{{ bhyve_mountpoint }}/{{ item.name }}/grub.installed"
  with_items: "{{ bhyve_vms }}"

- name: create device.installed.map
  template:
    src: device.installed.map
    dest: "{{ bhyve_mountpoint }}/{{ item.name }}/device.installed.map"
  with_items: "{{ bhyve_vms }}"
